/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package enterprise.itsupport.user;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Complaint;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class RaiseComplaint extends javax.swing.JPanel {

	MainJFrame ws;
	JPanel csp;

	/**
	 * Creates new form RaiseComplaint
	 */
	public RaiseComplaint(MainJFrame ws, JPanel csp) {
		this.ws = ws;
		this.csp = csp;
		initComponents();
		setBackground(Color.WHITE);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnBack5 = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtIssue = new javax.swing.JTextArea();
                jLabel3 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                txtReproduce = new javax.swing.JTextArea();
                btnRaise = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                txtTitle = new javax.swing.JTextField();

                btnBack5.setBackground(new java.awt.Color(255, 255, 255));
                btnBack5.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnBack5.setForeground(new java.awt.Color(51, 51, 51));
                btnBack5.setText("<< Back");
                btnBack5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBack5ActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
                jLabel1.setText("Raise a complaint");

                jLabel2.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                jLabel2.setText("What's the issue?*");

                txtIssue.setColumns(20);
                txtIssue.setRows(5);
                jScrollPane1.setViewportView(txtIssue);

                jLabel3.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                jLabel3.setText("How can we reproduce the issue?*");

                txtReproduce.setColumns(20);
                txtReproduce.setRows(5);
                jScrollPane2.setViewportView(txtReproduce);

                btnRaise.setBackground(new java.awt.Color(0, 102, 102));
                btnRaise.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnRaise.setForeground(new java.awt.Color(255, 255, 255));
                btnRaise.setText("Raise");
                btnRaise.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRaiseActionPerformed(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                jLabel4.setText("Title");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(64, 64, 64)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBack5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(393, 393, 393)
                                .addComponent(btnRaise, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63)
                                .addComponent(btnRaise, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(btnBack5)
                                .addGap(35, 35, 35))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnRaiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseActionPerformed
		String title = txtTitle.getText().trim();
		String issue = txtIssue.getText().trim();
		String reproduce = txtReproduce.getText().trim();

		if (title.length() == 0 || issue.length() == 0 || reproduce.length() == 0) {
			JOptionPane.showMessageDialog(this,"Please make sure no fields are empty");
			return;
		}

		Complaint c = new Complaint();
		c.setTitle(title);
		c.setHowToReproduce(reproduce);
		c.setMainIssue(issue);
		c.setUser(ws.getLoggedUser());

		ws.getComplaintDir().addComplaint(c);
		JOptionPane.showMessageDialog(this, "Complaint has been raised");

		txtTitle.setText("");
		txtIssue.setText("");
		txtReproduce.setText("");

        }//GEN-LAST:event_btnRaiseActionPerformed

        private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
                // TODO add your handling code here:
		csp.remove(this);
		((java.awt.CardLayout) csp.getLayout()).next(csp);
        }//GEN-LAST:event_btnBack5ActionPerformed



        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack5;
        private javax.swing.JButton btnRaise;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea txtIssue;
        private javax.swing.JTextArea txtReproduce;
        private javax.swing.JTextField txtTitle;
        // End of variables declaration//GEN-END:variables
}
