/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import enterprise.itsupport.admin.Complaints;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class AdminWorkspace extends javax.swing.JPanel {

	MainJFrame ws;
	/**
	 * Creates new form ResearchJPanel
	 */
	public AdminWorkspace(MainJFrame ws) {
		this.ws=ws;
		initComponents();
		this.ws.add(this);
		this.ws.pack();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                container = new javax.swing.JSplitPane();
                jPanel1 = new javax.swing.JPanel();
                btnLogout = new javax.swing.JButton();
                btnResearch = new javax.swing.JButton();
                btnHiring = new javax.swing.JButton();
                btnComplaints = new javax.swing.JButton();
                btnGrants = new javax.swing.JButton();
                btnUserActivity = new javax.swing.JButton();
                rightComponent = new javax.swing.JPanel();

                jPanel1.setBackground(new java.awt.Color(0, 51, 51));

                btnLogout.setBackground(new java.awt.Color(255, 255, 255));
                btnLogout.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnLogout.setForeground(new java.awt.Color(51, 51, 51));
                btnLogout.setText("Logout");
                btnLogout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLogoutActionPerformed(evt);
                        }
                });

                btnResearch.setBackground(new java.awt.Color(255, 255, 255));
                btnResearch.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnResearch.setForeground(new java.awt.Color(51, 51, 51));
                btnResearch.setText("Research analytics");
                btnResearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnResearchActionPerformed(evt);
                        }
                });

                btnHiring.setBackground(new java.awt.Color(255, 255, 255));
                btnHiring.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnHiring.setForeground(new java.awt.Color(51, 51, 51));
                btnHiring.setText("Hiring analytics");
                btnHiring.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHiringActionPerformed(evt);
                        }
                });

                btnComplaints.setBackground(new java.awt.Color(255, 255, 255));
                btnComplaints.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnComplaints.setForeground(new java.awt.Color(51, 51, 51));
                btnComplaints.setText("View complaints");
                btnComplaints.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnComplaintsActionPerformed(evt);
                        }
                });

                btnGrants.setBackground(new java.awt.Color(255, 255, 255));
                btnGrants.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnGrants.setForeground(new java.awt.Color(51, 51, 51));
                btnGrants.setText("Grant applications");
                btnGrants.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGrantsActionPerformed(evt);
                        }
                });

                btnUserActivity.setBackground(new java.awt.Color(255, 255, 255));
                btnUserActivity.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnUserActivity.setForeground(new java.awt.Color(51, 51, 51));
                btnUserActivity.setText("User activity");
                btnUserActivity.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUserActivityActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnResearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHiring, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnComplaints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGrants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUserActivity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(btnResearch)
                                .addGap(32, 32, 32)
                                .addComponent(btnHiring)
                                .addGap(38, 38, 38)
                                .addComponent(btnComplaints)
                                .addGap(37, 37, 37)
                                .addComponent(btnGrants)
                                .addGap(39, 39, 39)
                                .addComponent(btnUserActivity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                .addComponent(btnLogout)
                                .addGap(87, 87, 87))
                );

                container.setLeftComponent(jPanel1);

                rightComponent.setBackground(new java.awt.Color(0, 102, 102));
                rightComponent.setLayout(new java.awt.CardLayout());
                container.setRightComponent(rightComponent);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 1387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnComplaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintsActionPerformed
		rightComponent.removeAll();
		Complaints panel = new Complaints(ws, rightComponent);
		rightComponent.add("ConferencesJPanel", panel);
		((java.awt.CardLayout) rightComponent.getLayout()).next(rightComponent);
        }//GEN-LAST:event_btnComplaintsActionPerformed

        private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
                // TODO add your handling code here:
		this.ws.setLoggedUser(null);
		this.ws.getInitJPanel().setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_btnLogoutActionPerformed

        private void btnGrantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrantsActionPerformed
		rightComponent.removeAll();
		GrantApplications panel = new GrantApplications(ws, rightComponent);
		rightComponent.add("GrantApplicationJPanel", panel);
		((java.awt.CardLayout) rightComponent.getLayout()).next(rightComponent);
        }//GEN-LAST:event_btnGrantsActionPerformed

        private void btnHiringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHiringActionPerformed
		rightComponent.removeAll();
		HiringAnalytics panel = new HiringAnalytics(ws, rightComponent);
		rightComponent.add("HiringAnalytics", panel);
		((java.awt.CardLayout) rightComponent.getLayout()).next(rightComponent);
        }//GEN-LAST:event_btnHiringActionPerformed

        private void btnResearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResearchActionPerformed
		rightComponent.removeAll();
		ResearchAnalytics panel = new ResearchAnalytics(ws, rightComponent);
		rightComponent.add("HiringAnalytics", panel);
		((java.awt.CardLayout) rightComponent.getLayout()).next(rightComponent);
        }//GEN-LAST:event_btnResearchActionPerformed

        private void btnUserActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActivityActionPerformed
		rightComponent.removeAll();
		UserActivity panel = new UserActivity(ws, rightComponent);
		rightComponent.add("UserActivity", panel);
		((java.awt.CardLayout) rightComponent.getLayout()).next(rightComponent);
        }//GEN-LAST:event_btnUserActivityActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnComplaints;
        private javax.swing.JButton btnGrants;
        private javax.swing.JButton btnHiring;
        private javax.swing.JButton btnLogout;
        private javax.swing.JButton btnResearch;
        private javax.swing.JButton btnUserActivity;
        private javax.swing.JSplitPane container;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel rightComponent;
        // End of variables declaration//GEN-END:variables
}
