/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import java.awt.Color;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Complaint;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class Complaints extends javax.swing.JPanel {

	MainJFrame ws;
	JPanel csp;
	/**
	 * Creates new form Complaints
	 */
	public Complaints(MainJFrame ws, JPanel csp) {
		this.ws=ws;
		this.csp=csp;
		initComponents();
		setBackground(Color.WHITE);
		tbl.setRowHeight(30);
		tbl.getColumnModel().getColumn(4).setMaxWidth(0);

		populateTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                tbl = new javax.swing.JTable();
                pageTitle = new javax.swing.JLabel();
                btnSave = new javax.swing.JButton();

                tbl.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null}
                        },
                        new String [] {
                                "Complaint title", "Issue", "How to reproduce", "Response", ""
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                true, false, false, true, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(tbl);
                if (tbl.getColumnModel().getColumnCount() > 0) {
                        tbl.getColumnModel().getColumn(4).setResizable(false);
                }

                pageTitle.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                pageTitle.setText("View all complaints");

                btnSave.setBackground(new java.awt.Color(51, 0, 102));
                btnSave.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnSave.setForeground(new java.awt.Color(255, 255, 255));
                btnSave.setText("Save responses");
                btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSaveActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(45, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
		int R = tbl.getRowCount();
		int C = tbl.getColumnCount();

		// NUID header is at index 0
		for (int i = 0; i < R; ++i) {
			for (int j = 0; j < C; ++j) {
				String updatedResponse = (String) tbl.getValueAt(i, 3);
				String complaintId = (String) tbl.getValueAt(i, 4);

				Complaint c = ws.getComplaintDir().fetchById(complaintId);

				c.setAdminResponse(updatedResponse);
			}
		}
		populateTable();
		JOptionPane.showMessageDialog(this, "All responses saved!");

        }//GEN-LAST:event_btnSaveActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnSave;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel pageTitle;
        private javax.swing.JTable tbl;
        // End of variables declaration//GEN-END:variables

	private void populateTable() {

		DefaultTableModel table = (DefaultTableModel) tbl.getModel();

		int n = table.getRowCount();
		while (n-- > 0) {
			table.removeRow(n);
		}

//		List<ResearchGroup> groups = this.ws.getResearchGroups().getDir();
		List<Complaint> complaints = this.ws.getComplaintDir().getDir();

		int i = 1;
		for (Complaint c : complaints) {
			Vector<String> row = new Vector<>();
			row.add(c.getTitle());
			row.add(c.getDate());
			row.add(c.getHowToReproduce());
			row.add(c.getAdminResponse() == "NOT_YET_REPLIED" ? "Pending" : c.getAdminResponse());
			row.add(c.getId());

			table.addRow(row);
		}
	}
}
