/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package enterprise.research.collaboration;

import enterprise.scrutiny.grant.PreviousGrants;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.researcher.ResearchPaper;
import model.researcher.Researcher;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class ApplyGrant extends javax.swing.JPanel {

	MainJFrame ws;
	JPanel csp;
	Researcher r;

	/**
	 * Creates new form ApplyGrant
	 */
	public ApplyGrant(MainJFrame ws, JPanel csp) {
		this.ws = ws;
		this.csp = csp;
		this.r = this.ws.getResearcherDir().fetchByUser(this.ws.getLoggedUser());
		initComponents();
		setBackground(Color.WHITE);


		populateCombo();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pageTitle = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                comboPapers = new javax.swing.JComboBox<>();
                jLabel2 = new javax.swing.JLabel();
                txtFunds = new javax.swing.JTextField();
                btnApplyGrant = new javax.swing.JButton();
                btnViewGrants = new javax.swing.JButton();

                pageTitle.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
                pageTitle.setText("Apply for a grant");

                jLabel1.setText("Select the paper you want to apply a grant with*");

                comboPapers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabel2.setText("How much funds do you need? (in $) *");

                btnApplyGrant.setBackground(new java.awt.Color(255, 255, 255));
                btnApplyGrant.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnApplyGrant.setForeground(new java.awt.Color(51, 51, 51));
                btnApplyGrant.setText("Apply");
                btnApplyGrant.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnApplyGrantActionPerformed(evt);
                        }
                });

                btnViewGrants.setBackground(new java.awt.Color(0, 102, 102));
                btnViewGrants.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnViewGrants.setForeground(new java.awt.Color(255, 255, 255));
                btnViewGrants.setText("View previous grants >>");
                btnViewGrants.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnViewGrantsActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(btnApplyGrant, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(81, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFunds)
                                        .addComponent(comboPapers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewGrants, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboPapers, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(btnViewGrants, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129)
                                .addComponent(btnApplyGrant, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(138, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnApplyGrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyGrantActionPerformed
		String paperTitle = (String) comboPapers.getSelectedItem();
		String funds = txtFunds.getText().trim();

		this.ws.getResearchGroups().getPaperByResearcherAndTitle(r, paperTitle).addGrant(funds);

		txtFunds.setText("");

		JOptionPane.showMessageDialog(this, "Grant application for " + funds + " has been applied successfully.");

        }//GEN-LAST:event_btnApplyGrantActionPerformed

        private void btnViewGrantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGrantsActionPerformed

		PreviousGrants panel = new PreviousGrants(ws, csp);

		csp.add("PreviousGrants", panel);
		((java.awt.CardLayout) csp.getLayout()).next(csp);
        }//GEN-LAST:event_btnViewGrantsActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnApplyGrant;
        private javax.swing.JButton btnViewGrants;
        private javax.swing.JComboBox<String> comboPapers;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel pageTitle;
        private javax.swing.JTextField txtFunds;
        // End of variables declaration//GEN-END:variables

	private void populateCombo() {
		comboPapers.removeAllItems();

		for (ResearchPaper r : this.ws.getResearchGroups().getPaperByResearcher(r)) {
			comboPapers.addItem(r.getTitle());
		}
	}
}
