/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package enterprise.research.collaboration;

import enterprise.research.versioncontrol.VersionControlJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.researcher.ResearchPaper;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class EditingJPanel extends javax.swing.JPanel {

	MainJFrame ws = null;
	JPanel csp;
	ResearchPaper paper;

	/**
	 * Creates new form EditingJPanel
	 */
	public EditingJPanel(MainJFrame ws, ResearchPaper paper, JPanel csp) {
		this.ws = ws;
		this.paper = paper;
		this.csp=csp;
		initComponents();
		this.ws.add(this);
		this.ws.pack();

		txtAbstract.setLineWrap(true);
		txtResults.setLineWrap(true);
		txtConclusion.setLineWrap(true);
		txtIntro.setLineWrap(true);

		pageTitle.setText(paper.getTitle());

		populatePaperFields();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this cde. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pageTitle = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                txtAbstract = new javax.swing.JTextArea();
                btnBack = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                jScrollPane3 = new javax.swing.JScrollPane();
                txtIntro = new javax.swing.JTextArea();
                lblResults = new javax.swing.JLabel();
                jScrollPane4 = new javax.swing.JScrollPane();
                txtResults = new javax.swing.JTextArea();
                lblResults1 = new javax.swing.JLabel();
                jScrollPane5 = new javax.swing.JScrollPane();
                txtConclusion = new javax.swing.JTextArea();
                txtTitle = new javax.swing.JTextField();
                btnSave = new javax.swing.JButton();
                btnVC = new javax.swing.JButton();

                setBackground(new java.awt.Color(102, 51, 0));

                pageTitle.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
                pageTitle.setForeground(new java.awt.Color(255, 255, 255));
                pageTitle.setText("{paper_title}");

                jLabel2.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Title");

                jLabel3.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Abstract");

                txtAbstract.setColumns(20);
                txtAbstract.setFont(new java.awt.Font("DM Mono", 0, 15)); // NOI18N
                txtAbstract.setRows(5);
                jScrollPane2.setViewportView(txtAbstract);

                btnBack.setBackground(new java.awt.Color(255, 255, 255));
                btnBack.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnBack.setForeground(new java.awt.Color(51, 51, 51));
                btnBack.setText("<< Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Intro");

                txtIntro.setColumns(20);
                txtIntro.setFont(new java.awt.Font("DM Mono", 0, 15)); // NOI18N
                txtIntro.setRows(5);
                jScrollPane3.setViewportView(txtIntro);

                lblResults.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                lblResults.setForeground(new java.awt.Color(255, 255, 255));
                lblResults.setText("Results");

                txtResults.setColumns(20);
                txtResults.setFont(new java.awt.Font("DM Mono", 0, 15)); // NOI18N
                txtResults.setRows(5);
                jScrollPane4.setViewportView(txtResults);

                lblResults1.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                lblResults1.setForeground(new java.awt.Color(255, 255, 255));
                lblResults1.setText("Conclusion");

                txtConclusion.setColumns(20);
                txtConclusion.setFont(new java.awt.Font("DM Mono", 0, 15)); // NOI18N
                txtConclusion.setRows(5);
                jScrollPane5.setViewportView(txtConclusion);

                txtTitle.setFont(new java.awt.Font("DM Mono", 0, 15)); // NOI18N

                btnSave.setBackground(new java.awt.Color(51, 102, 0));
                btnSave.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnSave.setForeground(new java.awt.Color(255, 255, 255));
                btnSave.setText("Save changes");
                btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnVC.setBackground(new java.awt.Color(51, 0, 51));
                btnVC.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
                btnVC.setForeground(new java.awt.Color(255, 255, 255));
                btnVC.setText("Version control");
                btnVC.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnVCActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 41, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane5)
                                                        .addComponent(lblResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane4)
                                                        .addComponent(lblResults1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 816, Short.MAX_VALUE)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(txtTitle))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblResults1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBack)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
		// TODO add your handling code here:
		csp.remove(this);
		((java.awt.CardLayout) csp.getLayout()).next(csp);
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
		String title = txtTitle.getText().trim();
		String intro = txtIntro.getText().trim();
		String abstractText = txtAbstract.getText().trim();
		String results = txtResults.getText().trim();
		String conclusion = txtConclusion.getText().trim();

		// validation here (null validation)


		paper.setConclusion(conclusion);
		paper.setResults(results);
		
		paper.setTitle(title);
		paper.setIntro(intro);
		paper.setAbstractText(abstractText);

		String comments = JOptionPane.showInputDialog(this, "Any comments?");

		paper.addHistory(this.ws.getLoggedUser(), comments.length() > 0 ? comments : "N/A");

		JOptionPane.showMessageDialog(this, "Paper was saved successfully!");
        }//GEN-LAST:event_btnSaveActionPerformed

        private void btnVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVCActionPerformed
		VersionControlJPanel vc = new VersionControlJPanel(ws, csp, paper);

		csp.add("VersionControl", vc);
		((java.awt.CardLayout) csp.getLayout()).next(csp);
		
        }//GEN-LAST:event_btnVCActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnSave;
        private javax.swing.JButton btnVC;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JLabel lblResults;
        private javax.swing.JLabel lblResults1;
        private javax.swing.JLabel pageTitle;
        private javax.swing.JTextArea txtAbstract;
        private javax.swing.JTextArea txtConclusion;
        private javax.swing.JTextArea txtIntro;
        private javax.swing.JTextArea txtResults;
        private javax.swing.JTextField txtTitle;
        // End of variables declaration//GEN-END:variables

	private void populatePaperFields() {
		txtTitle.setText(paper.getTitle());
		txtIntro.setText(paper.getIntro());
		txtAbstract.setText(paper.getAbstractText());
		txtResults.setText(paper.getResults());
		txtConclusion.setText(paper.getConclusion());
		
	}
}
