/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package enterprise.research.collaboration;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Email;
import model.researcher.Researcher;
import ui.ButtonCellRenderer;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class MyEmails extends javax.swing.JPanel {

	MainJFrame ws;
	Researcher r;
	JPanel csp;
	/**
	 * Creates new form MyEmails
	 */
	public MyEmails(MainJFrame ws, Researcher r, JPanel csp) {
		this.ws=ws;
		this.r=r;
		this.csp=csp;

		initComponents();

		setBackground(Color.WHITE);

		tbl.setRowHeight(30);
		tbl.getColumnModel().getColumn(5).setMaxWidth(0);


		Action actionView = new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				try {
					int selectedRowIndex = tbl.getSelectedRow();
					String emailId = (String) tbl.getValueAt(selectedRowIndex, 5);
					Email email = r.getEmailById(emailId);

					ViewEmail panel = new ViewEmail(ws, email, csp);

					csp.add("ViewEmail", panel);
					((java.awt.CardLayout) csp.getLayout()).next(csp);
				} catch (Exception exception) {
					exception.printStackTrace();
					JOptionPane.showMessageDialog(null, "There was an issue. Please try again.");
				}
			}
		};

		ButtonCellRenderer completeButton = new ButtonCellRenderer(tbl, actionView, 3);

		populateTbl();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                tbl = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();

                tbl.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null}
                        },
                        new String [] {
                                "Sender", "Subject", "Message", "Action", "Date", ""
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false, true, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tbl.setColumnSelectionAllowed(true);
                jScrollPane1.setViewportView(tbl);
                tbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                if (tbl.getColumnModel().getColumnCount() > 0) {
                        tbl.getColumnModel().getColumn(4).setResizable(false);
                        tbl.getColumnModel().getColumn(5).setResizable(false);
                }

                jLabel1.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
                jLabel1.setText("My emails");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tbl;
        // End of variables declaration//GEN-END:variables

	private void populateTbl() {

		DefaultTableModel table = (DefaultTableModel) tbl.getModel();

		int n = table.getRowCount();
		while (n-- > 0) {
			table.removeRow(n);
		}

		int i = 1;
		for (Email email : this.r.getEmails()) {
			Vector<String> row = new Vector<>();
			row.add(email.getSenderEmail());
			row.add(email.getSubject());
			row.add(email.getMessage());
			row.add("View message");
			row.add(email.getDate());
			row.add(email.getId());

			table.addRow(row);
		}
	}
}
