/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package enterprise.research.collaboration;

import enterprise.research.collaboration.EditingJPanel;
import constants.PaperStatus;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.print.Paper;
import java.util.List;
import java.util.StringJoiner;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.researcher.ResearchGroup;
import model.researcher.ResearchPaper;
import model.researcher.Researcher;
import ui.ButtonCellRenderer;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class MyResearch extends javax.swing.JPanel {

	MainJFrame ws = null;
	JPanel csp;

	/**
	 * Creates new form MyResearch
	 */
	public MyResearch(MainJFrame ws, JPanel csp) {
		this.ws = ws;
		this.csp = csp;
		initComponents();

		setBackground(Color.WHITE);

		tbl.setRowHeight(30);

		this.ws.add(this);
		this.ws.pack();

		Action actionEdit = new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				try {
					int selectedRowIndex = tbl.getSelectedRow();
					String groupId = (String) tbl.getValueAt(selectedRowIndex, 0);
					ResearchPaper paper = ws.getResearchGroups().getById(groupId).getPaper();

					EditingJPanel editing = new EditingJPanel(ws, paper, csp);

					csp.add("Editing", editing);
					((java.awt.CardLayout) csp.getLayout()).next(csp);
				} catch (Exception exception) {
					exception.printStackTrace();
					JOptionPane.showMessageDialog(null, "There was an issue. Please try again.");
				}
			}
		};

		Action actionPublish = new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				try {
					int selectedRowIndex = tbl.getSelectedRow();
					String groupId = (String) tbl.getValueAt(selectedRowIndex, 0);
					ResearchPaper paper = ws.getResearchGroups().getById(groupId).getPaper();

					paper.setStatus(PaperStatus.UNDER_REVIEW);

					populateTable();
				} catch (Exception exception) {
					exception.printStackTrace();
					JOptionPane.showMessageDialog(null, "There was an issue. Please try again.");
				}
			}
		};

		ButtonCellRenderer completeButton = new ButtonCellRenderer(tbl, actionEdit, 3);
		ButtonCellRenderer publishButton = new ButtonCellRenderer(tbl, actionPublish, 4);

		populateTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pageTitle = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbl = new javax.swing.JTable();

                pageTitle.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
                pageTitle.setText("You can find all your research here!");

                tbl.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null}
                        },
                        new String [] {
                                "Serial number", "Paper name", "Collaborators", "Edit", "Send for publishing", "Total citations"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false, true, true, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tbl.setColumnSelectionAllowed(true);
                jScrollPane1.setViewportView(tbl);
                tbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(192, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel pageTitle;
        private javax.swing.JTable tbl;
        // End of variables declaration//GEN-END:variables

	private void populateTable() {
		DefaultTableModel table = (DefaultTableModel) tbl.getModel();

		int n = table.getRowCount();
		while (n-- > 0) {
			table.removeRow(n);
		}

//		List<ResearchGroup> groups = this.ws.getResearchGroups().getDir();
		Researcher r = this.ws.getResearcherDir().fetchByEmail(this.ws.getLoggedUser().getEmail());
		List<ResearchGroup> groups = this.ws.getResearchGroups().getDirByResearcher(r);

		int i = 1;
		for (ResearchGroup rg : groups) {
			Vector<String> row = new Vector<>();
			row.add(rg.getUuid());
			row.add(rg.getPaper().getTitle());
			row.add(listToString(rg.getGroup()));
			row.add("Edit paper");

			String verdict = "";
			if (rg.getPaper().getStatus() == PaperStatus.CHANGES_REQUESTED) {
				verdict = "Changes requested";
			} else if (rg.getPaper().getStatus() == PaperStatus.PUBLISHED) {
				verdict = "Published";
			} else if (rg.getPaper().getStatus() == PaperStatus.UNDER_REVIEW) {
				verdict = "Under review";
			} else if (rg.getPaper().getStatus() == PaperStatus.DRAFT) {
				verdict = "Draft";
			}

			row.add(verdict);
			row.add(String.valueOf(rg.getPaper().getCitations().size()));

			table.addRow(row);
		}
	}

	public static String listToString(List<Researcher> list) {
		StringJoiner joiner = new StringJoiner(", ");
		for (Researcher r : list) {
			joiner.add(r.getUser().getFirstName() + " " + r.getUser().getLastName());

		}
		return joiner.toString();
	}

}
