/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import constants.Role;
import enterprise.auth.Auth;
import javax.swing.JOptionPane;
import model.User;
import ui.admin.AdminWorkspace;
import enterprise.feedbackUser.FeedbackUserWorkspace;
import enterprise.hiring.HiringWorkspace;
import enterprise.research.collaboration.ResearchWorkspace;
import enterprise.scrutiny.verdict.ScrutinyWorkspace;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author drag
 */
public class LoginJPanel extends javax.swing.JPanel {

	MainJFrame ws= null;


	/**
	 * Creates new form LoginJPanel
	 */
	public LoginJPanel(MainJFrame ws) {
		this.ws = ws;

		initComponents();

		img.setIcon(new ImageIcon("resources/login.png"));

		setBackground(Color.WHITE);

		this.ws.add(this);
		this.ws.pack();


	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                txtEmail = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                txtPassword = new javax.swing.JPasswordField();
                jLabel3 = new javax.swing.JLabel();
                btnBack = new javax.swing.JButton();
                btnLogin = new javax.swing.JButton();
                img = new javax.swing.JLabel();

                setBackground(new java.awt.Color(204, 153, 0));

                jLabel1.setText("Email address*");

                txtEmail.setFont(new java.awt.Font("Hurmit Nerd Font Mono", 0, 15)); // NOI18N

                jLabel2.setText("Password*");

                txtPassword.setFont(new java.awt.Font("Hurmit Nerd Font Mono", 0, 15)); // NOI18N

                jLabel3.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                jLabel3.setText("Login");

                btnBack.setText("<< Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                btnLogin.setBackground(new java.awt.Color(0, 102, 51));
                btnLogin.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnLogin.setForeground(new java.awt.Color(255, 255, 255));
                btnLogin.setText("Login");
                btnLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLoginActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnBack)
                                        .addComponent(txtPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
                );

                layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogin, txtPassword});

                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnBack)
                                .addContainerGap(202, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogin, txtEmail, txtPassword});

        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
		this.ws.getInitJPanel().setVisible(true);
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
		// TODO add your handling code here:
		String email = txtEmail.getText().trim();
		String password = txtPassword.getText().trim();

		if (!Auth.validateEmail(email)) {
			JOptionPane.showMessageDialog(this, "Please enter a proper email");
			return;
		}

//		if (password.length() < 7) {
//			JOptionPane.showMessageDialog(this, "Ensure password is atleast 7 characters long.");
//			return;
//		}


		User userProfile = ws.getUserDir().login(email, password);

		if (userProfile == null) {
			JOptionPane.showMessageDialog(this, "No such user, please check email and password");
			return;
		}

		if (!userProfile.isEnabled()) {
			JOptionPane.showMessageDialog(this, "Your profile is disabled at the moment! Please contact the admin for further information.");
			return;
		}

		ws.setLoggedUser(userProfile);

		if (userProfile.getRole() == Role.RESEARCHER) {
			ResearchWorkspace researchWS = new ResearchWorkspace(ws);
			researchWS.setVisible(true);
			this.setVisible(false);
		}
		else if (userProfile.getRole()== Role.FEEDBACK_USER) {
			FeedbackUserWorkspace fdbk = new FeedbackUserWorkspace(ws);
			fdbk.setVisible(true);
			this.setVisible(false);
		}
		else if (userProfile.getRole()== Role.ADMIN) {
			AdminWorkspace adminWS = new AdminWorkspace(ws);
			adminWS.setVisible(true);
			this.setVisible(false);
		}
		else if (userProfile.getRole() == Role.HIRING_MANAGER) {
			HiringWorkspace hiringWS = new HiringWorkspace(ws);
			hiringWS.setVisible(true);
			this.setVisible(false);
		}
		else if (userProfile.getRole() == Role.SCRUTINY_ASSCOCIATION) {
			ScrutinyWorkspace scrutinyWS = new ScrutinyWorkspace(ws);
			scrutinyWS.setVisible(true);
			this.setVisible(false);
		}


        }//GEN-LAST:event_btnLoginActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnLogin;
        private javax.swing.JLabel img;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JPasswordField txtPassword;
        // End of variables declaration//GEN-END:variables
}
