/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import config.Config;
import constants.Role;
import directory.ComplaintDirectory;
import directory.ConferenceDirectory;
import directory.ResearchGroupDirectory;
import directory.ResearchPaperDirectory;
import directory.ResearcherDirectory;
import directory.UserDirectory;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.User;

/**
 *
 * @author drag
 */
public class MainJFrame extends javax.swing.JFrame {

	User loggedUser;
	UserDirectory userDir;
	ResearcherDirectory researcherDir;
	ResearchGroupDirectory researchGroups;
	ResearchPaperDirectory paperDir;
	ConferenceDirectory conferenceDir;
	ComplaintDirectory complaintDir;
	/**
	 * Creates new form MainJFrame
	 */
	public MainJFrame() {
		initComponents();

		img.setIcon(new ImageIcon("resources/collaborate.jpeg"));

		initJPanel.setBackground(Color.WHITE);

		userDir = Config.initializeUserDir();
		researcherDir = Config.initializeResearcherDir(userDir);
		researchGroups = Config.initializeResearchGroupDir(researcherDir);
		paperDir = Config.initializePaperDir(researchGroups);
		conferenceDir = Config.initializeConferenceDir();
		complaintDir = Config.initializeComplaintDir();

	}

	public ComplaintDirectory getComplaintDir() {
		return complaintDir;
	}

	public ResearchPaperDirectory getPaperDir() {
		return paperDir;
	}

	public UserDirectory getUserDir() {
		return userDir;
	}

	public ResearcherDirectory getResearcherDir() {
		return researcherDir;
	}

	public ResearchGroupDirectory getResearchGroups() {
		return researchGroups;
	}

	public User getLoggedUser() {
		return loggedUser;
	}

	public void setLoggedUser(User loggedUser) {
		this.loggedUser = loggedUser;
	}


	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                jToolBar1 = new javax.swing.JToolBar();
                initJPanel = new javax.swing.JPanel();
                btnLogin = new javax.swing.JButton();
                btnRegister = new javax.swing.JButton();
                img = new javax.swing.JLabel();

                jToolBar1.setRollover(true);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new java.awt.GridBagLayout());

                btnLogin.setBackground(new java.awt.Color(0, 0, 0));
                btnLogin.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnLogin.setForeground(new java.awt.Color(255, 255, 255));
                btnLogin.setText("Login");
                btnLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLoginActionPerformed(evt);
                        }
                });

                btnRegister.setBackground(new java.awt.Color(0, 0, 0));
                btnRegister.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnRegister.setForeground(new java.awt.Color(255, 255, 255));
                btnRegister.setText("Register");
                btnRegister.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegisterActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout initJPanelLayout = new javax.swing.GroupLayout(initJPanel);
                initJPanel.setLayout(initJPanelLayout);
                initJPanelLayout.setHorizontalGroup(
                        initJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(initJPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addGroup(initJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(567, Short.MAX_VALUE))
                );
                initJPanelLayout.setVerticalGroup(
                        initJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(initJPanelLayout.createSequentialGroup()
                                .addGroup(initJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(initJPanelLayout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(initJPanelLayout.createSequentialGroup()
                                                .addGap(167, 167, 167)
                                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(546, Short.MAX_VALUE))
                );

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.ipadx = 561;
                gridBagConstraints.ipady = 540;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
                getContentPane().add(initJPanel, gridBagConstraints);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
                // TODO add your handling code here:
		LoginJPanel login = new LoginJPanel(this);

		initJPanel.setVisible(false);
		login.setVisible(true);

        }//GEN-LAST:event_btnLoginActionPerformed

        private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
                // TODO add your handling code here:
		RegisterJPanel register = new RegisterJPanel(this);
		initJPanel.setVisible(false);
		register.setVisible(true);
        }//GEN-LAST:event_btnRegisterActionPerformed

	public ConferenceDirectory getConferenceDir() {
		return conferenceDir;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainJFrame().setVisible(true);
			}
		});
	}

	public JPanel getInitJPanel() {
		return initJPanel;
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnLogin;
        private javax.swing.JButton btnRegister;
        private javax.swing.JLabel img;
        private javax.swing.JPanel initJPanel;
        private javax.swing.JToolBar jToolBar1;
        // End of variables declaration//GEN-END:variables
}
