/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import constants.Role;
import directory.UserDirectory;
import javax.swing.JOptionPane;
import model.User;
import ui.admin.AdminWorkarea;
import ui.certificationauth.CertAuthWorkArea;
import ui.employer.EmployerWorkarea;
import ui.professor.ProfessorWorkarea;
import ui.student.StudentWorkarea;

/**
 *
 * @author drag
 */
public class LoginJPanel extends javax.swing.JPanel {

	private MainJFrame workSpace;
	private UserDirectory userDir;

	/**
	 * Creates new form LoginJPanel
	 *
	 * @param workSpace
	 */
	public LoginJPanel(MainJFrame workSpace) {
		initComponents();

		this.workSpace = workSpace;
		this.userDir = this.workSpace.getUserDir();

		this.workSpace.add(this);
		this.workSpace.pack();

		String txtRole = "student";                          // default role

		switch (this.workSpace.getRole()) {
			case ADMIN:
				txtRole = "admin";
				break;
			case STUDENT:
				txtRole = "student";
				break;
			case PROFESSOR:
				txtRole = "professor";
				break;
			case EMPLOYER:
				txtRole = "employer";
				break;
			case CERTIFICATION_AUTH:
				txtRole = "certification authority";
				break;
		}
		this.pageTitle.setText("Login as a " + txtRole);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        pageTitle = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblUserName.setBackground(java.awt.Color.cyan);
        lblUserName.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName.setText("Username :");

        lblPassword.setBackground(java.awt.Color.cyan);
        lblPassword.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password :");

        btnLogin.setBackground(java.awt.Color.lightGray);
        btnLogin.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setBackground(java.awt.Color.lightGray);
        btnRegister.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        pageTitle.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        pageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageTitle.setText("Login as a");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Don't have an account?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtPassword)
                            .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(222, 222, 222))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPassword, txtUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addGap(5, 5, 5)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogin, btnRegister});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtPassword, txtUsername});

    }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
		this.workSpace.getInitJPanel().setVisible(true);
		this.setVisible(false);
		this.workSpace.setRole(null);
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
		RegisterJPanel registerPage = new RegisterJPanel(this.workSpace);
		this.setVisible(false);
		registerPage.setVisible(true);
        }//GEN-LAST:event_btnRegisterActionPerformed

        private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
		String userName = txtUsername.getText().trim();
		String password = txtPassword.getText().trim();

		User user = this.userDir.getUser(userName, password);

		// validations	
		if (txtUsername.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(this, "Please enter Username to login", "Validation Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		if (txtPassword.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(this, "Please enter Password to Login", "Validation Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		if (user == null) {
			JOptionPane.showMessageDialog(this, "There was an issue logging you in! Please try again.");
			txtUsername.setText("");
			txtPassword.setText("");
			return;
		}

		if (user.getRole() == Role.STUDENT && this.workSpace.getRole() == Role.STUDENT) {
			StudentWorkarea studentWorkarea = new StudentWorkarea(this.workSpace, user);

			this.workSpace.setUser(user);        // store session data
			studentWorkarea.setVisible(true);
			this.setVisible(false);
		} else if (user.getRole() == Role.PROFESSOR && this.workSpace.getRole() == Role.PROFESSOR) {
			ProfessorWorkarea profWorkarea = new ProfessorWorkarea(this.workSpace, user);

			this.workSpace.setUser(user);     // store session data
			profWorkarea.setVisible(true);
			this.setVisible(false);
		} else if (user.getRole() == Role.ADMIN && this.workSpace.getRole() == Role.ADMIN) {
			AdminWorkarea adminWorkarea = new AdminWorkarea(this.workSpace);

			this.workSpace.setUser(user);     // store session data
			adminWorkarea.setVisible(true);
			this.setVisible(false);

		} else if (user.getRole() == Role.CERTIFICATION_AUTH && this.workSpace.getRole() == Role.CERTIFICATION_AUTH) {
			CertAuthWorkArea certAuthWorkarea = new CertAuthWorkArea(this.workSpace);

			this.workSpace.setUser(user);     // store session data
			certAuthWorkarea.setVisible(true);
			this.setVisible(false);
		} else if (user.getRole() == Role.EMPLOYER && this.workSpace.getRole() == Role.EMPLOYER) {
			EmployerWorkarea employerWorkarea = new EmployerWorkarea(this.workSpace);

			this.workSpace.setUser(user);     // store session data
			employerWorkarea.setVisible(true);
			this.setVisible(false);
		} else {
			JOptionPane.showMessageDialog(this, "You are not authorized to login as a different user.");
			txtUsername.setText("");
			txtPassword.setText("");
			return;
		}

        }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
