package ui;

import constants.Role;
import directory.ProfessorDirectory;
import directory.StudentDirectory;
import directory.UniClassDirectory;
import directory.UserDirectory;
import javax.swing.JPanel;
import model.User;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

	private UserDirectory userDir;
	private StudentDirectory studentDir;
	private ProfessorDirectory profDir;
	private UniClassDirectory uniClassDir;
	private Role role;
	private User user;

	/**
	 * Creates new form LoginJFrame
	 */
	public MainJFrame() {
		initComponents();

		this.userDir = new UserDirectory();
		this.studentDir = new StudentDirectory();
		this.profDir = new ProfessorDirectory();
		this.uniClassDir = new UniClassDirectory();

		this.studentDir.inheritData(this.userDir);
		this.profDir.inheritData(this.userDir);
		this.uniClassDir.inheritData(profDir);


	}
		
	public UniClassDirectory getUniClassDir() {
		return uniClassDir;
	}

	public UserDirectory getUserDir() {
		return userDir;
	}

	public StudentDirectory getStudentDir() {
		return studentDir;
	}

	public ProfessorDirectory getProfDir() {
		return profDir;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public JPanel getInitJPanel() {
		return initJPanel;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                initJPanel = new javax.swing.JPanel();
                pageTitle = new javax.swing.JLabel();
                btnLearn = new javax.swing.JButton();
                btnTeach = new javax.swing.JButton();
                btnAdmin = new javax.swing.JButton();
                btnTranscript = new javax.swing.JButton();
                btnEmployer = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new java.awt.GridBagLayout());

                initJPanel.setBackground(new java.awt.Color(255, 204, 51));
                initJPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                pageTitle.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
                pageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                pageTitle.setText("Digital EdHub");

                btnLearn.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnLearn.setText("I want to learn");
                btnLearn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLearnActionPerformed(evt);
                        }
                });

                btnTeach.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnTeach.setText("I want to teach");
                btnTeach.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTeachActionPerformed(evt);
                        }
                });

                btnAdmin.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnAdmin.setText("Admin");
                btnAdmin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAdminActionPerformed(evt);
                        }
                });

                btnTranscript.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnTranscript.setText("Certificate authority");
                btnTranscript.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTranscriptActionPerformed(evt);
                        }
                });

                btnEmployer.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnEmployer.setText("Employer");
                btnEmployer.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEmployerActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout initJPanelLayout = new javax.swing.GroupLayout(initJPanel);
                initJPanel.setLayout(initJPanelLayout);
                initJPanelLayout.setHorizontalGroup(
                        initJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initJPanelLayout.createSequentialGroup()
                                .addGap(749, 749, 749)
                                .addGroup(initJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnTeach, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(initJPanelLayout.createSequentialGroup()
                                                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(763, 763, 763))
                );
                initJPanelLayout.setVerticalGroup(
                        initJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(initJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTeach, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addGroup(initJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnEmployer)
                                        .addComponent(btnTranscript)
                                        .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(800, 800, 800))
                );

                initJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdmin, btnEmployer, btnLearn, btnTranscript});

                getContentPane().add(initJPanel, new java.awt.GridBagConstraints());

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnActionPerformed
		this.role = Role.STUDENT;
		LoginJPanel loginPage = new LoginJPanel(this);
		initJPanel.setVisible(false);
		loginPage.setVisible(true);
        }//GEN-LAST:event_btnLearnActionPerformed

    private void btnTeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeachActionPerformed
		this.role = Role.PROFESSOR;
		LoginJPanel loginPage = new LoginJPanel(this);
		initJPanel.setVisible(false);
		loginPage.setVisible(true);
    }//GEN-LAST:event_btnTeachActionPerformed

        private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
		this.role = Role.ADMIN;
		LoginJPanel loginPage = new LoginJPanel(this);
		initJPanel.setVisible(false);
		loginPage.setVisible(true);
        }//GEN-LAST:event_btnAdminActionPerformed

        private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
		this.role = Role.CERTIFICATION_AUTH;
		LoginJPanel loginPage = new LoginJPanel(this);
		initJPanel.setVisible(false);
		loginPage.setVisible(true);
        }//GEN-LAST:event_btnTranscriptActionPerformed

        private void btnEmployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployerActionPerformed
		this.role = Role.EMPLOYER;
		LoginJPanel loginPage = new LoginJPanel(this);
		initJPanel.setVisible(false);
		loginPage.setVisible(true);
        }//GEN-LAST:event_btnEmployerActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainJFrame().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdmin;
        private javax.swing.JButton btnEmployer;
        private javax.swing.JButton btnLearn;
        private javax.swing.JButton btnTeach;
        private javax.swing.JButton btnTranscript;
        private javax.swing.JPanel initJPanel;
        private javax.swing.JLabel pageTitle;
        // End of variables declaration//GEN-END:variables
}
