/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.professor;

import model.User;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class EditProfileJPanel extends javax.swing.JPanel {

	private MainJFrame workSpace = null;
	/**
	 * 
	 * Creates new form EditProfileJPanel
	 */
	public EditProfileJPanel(MainJFrame workSpace) {
		initComponents();

		this.workSpace = workSpace;

		this.workSpace.add(this);
		this.workSpace.pack();
		
		this.populateFields();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pageTitle = new javax.swing.JLabel();
                lblFirstName = new javax.swing.JLabel();
                txtFirstName = new javax.swing.JTextField();
                lblEmail = new javax.swing.JLabel();
                txtEmail = new javax.swing.JTextField();
                lblAddressLine1 = new javax.swing.JLabel();
                txtAddressLine1 = new javax.swing.JTextField();
                lblUserName = new javax.swing.JLabel();
                txtUserName = new javax.swing.JTextField();
                txtAddressLine2 = new javax.swing.JTextField();
                lblAddressLine2 = new javax.swing.JLabel();
                txtPhone = new javax.swing.JTextField();
                lblPhone = new javax.swing.JLabel();
                txtLastName = new javax.swing.JTextField();
                lblLastName = new javax.swing.JLabel();

                pageTitle.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                pageTitle.setText("Your profile");

                lblFirstName.setBackground(java.awt.Color.cyan);
                lblFirstName.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lblFirstName.setText("First name");

                lblEmail.setBackground(java.awt.Color.cyan);
                lblEmail.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lblEmail.setText("Email");

                lblAddressLine1.setBackground(java.awt.Color.cyan);
                lblAddressLine1.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                lblAddressLine1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lblAddressLine1.setText("Address line 1");

                lblUserName.setBackground(java.awt.Color.cyan);
                lblUserName.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lblUserName.setText("Username");

                lblAddressLine2.setBackground(java.awt.Color.cyan);
                lblAddressLine2.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                lblAddressLine2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lblAddressLine2.setText("Address line 2");

                lblPhone.setBackground(java.awt.Color.cyan);
                lblPhone.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lblPhone.setText("Phone");

                lblLastName.setBackground(java.awt.Color.cyan);
                lblLastName.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                lblLastName.setText("Last name");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(230, 230, 230)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(txtAddressLine1)
                                                                                .addComponent(lblAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(txtEmail)
                                                                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(txtFirstName)
                                                                                .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(75, 75, 75)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(txtAddressLine2)
                                                                                .addComponent(lblAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(txtPhone)
                                                                                .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(txtLastName)
                                                                                .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(txtUserName)
                                                                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(36, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblFirstName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblLastName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblEmail)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPhone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblAddressLine1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblAddressLine2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lblUserName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(283, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel lblAddressLine1;
        private javax.swing.JLabel lblAddressLine2;
        private javax.swing.JLabel lblEmail;
        private javax.swing.JLabel lblFirstName;
        private javax.swing.JLabel lblLastName;
        private javax.swing.JLabel lblPhone;
        private javax.swing.JLabel lblUserName;
        private javax.swing.JLabel pageTitle;
        private javax.swing.JTextField txtAddressLine1;
        private javax.swing.JTextField txtAddressLine2;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtFirstName;
        private javax.swing.JTextField txtLastName;
        private javax.swing.JTextField txtPhone;
        private javax.swing.JTextField txtUserName;
        // End of variables declaration//GEN-END:variables

	private void populateFields() {
		User u = this.workSpace.getUser();

		txtFirstName.setText(u.getPerson().getFirstName());
		txtLastName.setText(u.getPerson().getLastName());
		txtEmail.setText(u.getPerson().getEmail());
		txtAddressLine1.setText(u.getPerson().getAddressLine1());
		txtAddressLine2.setText(u.getPerson().getAddressLine2());
		txtPhone.setText(u.getPerson().getPhone());
		txtUserName.setText(u.getUserName());
		
	}
}
