/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.professor;

import java.util.List;
import javax.swing.JOptionPane;
import model.Notification;
import model.UniClass;
import model.student.Student;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class NotificationEditorJPanel extends javax.swing.JPanel {

	private MainJFrame workSpace;
	private TermScheduleJPanel parent;
	private UniClass uniClass;	
	/**
	 * Creates new form NotificationEditorJPanel
	 */
	public NotificationEditorJPanel(MainJFrame workSpace, TermScheduleJPanel parent) {
		this.workSpace = workSpace;
		this.parent = parent;

		initComponents();

		this.workSpace.add(this);
		this.workSpace.pack();
		
//		pageTitle.setText(uniClass.getFullCourseName());
		this.txtSubject.setText("");
		this.txtMessage.setText("");

	}

	public UniClass getUniClass() {
		return uniClass;
	}

	public void setUniClass(UniClass uniClass) {
		this.uniClass = uniClass;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnSend = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();
                lblSubject = new javax.swing.JLabel();
                txtSubject = new javax.swing.JTextField();
                lblMessage = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtMessage = new javax.swing.JTextArea();

                btnSend.setText("Send notification");
                btnSend.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSendActionPerformed(evt);
                        }
                });

                btnCancel.setText("Cancel");
                btnCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelActionPerformed(evt);
                        }
                });

                lblSubject.setText("Subject");

                lblMessage.setText("Message");

                txtMessage.setColumns(20);
                txtMessage.setRows(5);
                jScrollPane1.setViewportView(txtMessage);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtSubject)
                                                        .addComponent(lblMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(237, 237, 237)
                                                .addComponent(btnCancel)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 239, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lblSubject)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancel))
                                .addGap(17, 17, 17))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		parent.setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_btnCancelActionPerformed

        private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
		// get all students enrolled in the course - then add notification in each student instance
		List<Student> students = this.workSpace.getStudentDir().getStudentsByUniClass(uniClass);

		String subject = txtSubject.getText().trim();
		String message = txtMessage.getText().trim();

		for (Student s : students) {
			s.addNotification(new Notification(uniClass, subject, message));
		}

		txtSubject.setText("");
		txtMessage.setText("");

		JOptionPane.showMessageDialog(null, "Notification sent successfully!");
		
		parent.setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_btnSendActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSend;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblMessage;
        private javax.swing.JLabel lblSubject;
        private javax.swing.JTextArea txtMessage;
        private javax.swing.JTextField txtSubject;
        // End of variables declaration//GEN-END:variables
}
