/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package enterprise.research.database;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.StringJoiner;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.researcher.ResearchGroup;
import model.researcher.ResearchPaper;
import model.researcher.Researcher;
import ui.ButtonCellRenderer;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class BrowsePapers extends javax.swing.JPanel {

	MainJFrame ws;
	JPanel csp;

	/**
	 * Creates new form BrowsePapers
	 */
	public BrowsePapers(MainJFrame ws, JPanel csp) {
		this.ws = ws;
		this.csp = csp;
		initComponents();

		this.ws.add(this);
		this.ws.pack();

		setBackground(Color.WHITE);

		tbl.setRowHeight(30);
		tbl.getColumnModel().getColumn(3).setMaxWidth(0);

		
		Action actionRead = new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				try {
					int selectedRowIndex = tbl.getSelectedRow();
					String groupId = (String) tbl.getValueAt(selectedRowIndex, 3);
					ResearchPaper paper = ws.getResearchGroups().getById(groupId).getPaper();

					ViewPaper panel = new ViewPaper(ws, paper, csp);

					csp.add("ViewPaper", panel);
					((java.awt.CardLayout) csp.getLayout()).next(csp);
				} catch (Exception exception) {
					exception.printStackTrace();
					JOptionPane.showMessageDialog(null, "There was an issue. Please try again.");
				}
			}
		};

		ButtonCellRenderer completeButton = new ButtonCellRenderer(tbl, actionRead, 2);

		populateTbl();

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pageTitle = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbl = new javax.swing.JTable();

                pageTitle.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
                pageTitle.setText("Browse papers");

                tbl.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Paper title", "Collaborators", "Read paper", ""
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, true, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tbl.setColumnSelectionAllowed(true);
                jScrollPane1.setViewportView(tbl);
                tbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                if (tbl.getColumnModel().getColumnCount() > 0) {
                        tbl.getColumnModel().getColumn(3).setResizable(false);
                }

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
                                        .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(27, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel pageTitle;
        private javax.swing.JTable tbl;
        // End of variables declaration//GEN-END:variables

	private void populateTbl() {

		DefaultTableModel table = (DefaultTableModel) tbl.getModel();

		int n = table.getRowCount();
		while (n-- > 0) {
			table.removeRow(n);
		}

		Researcher r = this.ws.getResearcherDir().fetchByEmail(this.ws.getLoggedUser().getEmail());
		List<ResearchGroup> groups = this.ws.getResearchGroups().getDir();

		int i = 1;
		for (ResearchGroup rg : groups) {
			Vector<String> row = new Vector<>();
			row.add(rg.getPaper().getTitle());
			row.add(listToString(rg.getGroup()));
			row.add("Read paper");
			row.add(rg.getUuid());

			table.addRow(row);
		}
	}

	public static String listToString(List<Researcher> list) {
		StringJoiner joiner = new StringJoiner(", ");
		for (Researcher r : list) {
			joiner.add(r.getUser().getFirstName() + " " + r.getUser().getLastName());

		}
		return joiner.toString();
	}
}
