/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package enterprise.research.database;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.researcher.Researcher;
import ui.ButtonCellRenderer;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class CreateGroup extends javax.swing.JPanel {

	MainJFrame ws;
	JPanel csp;

	/**
	 * Creates new form CreateGroup
	 */
	public CreateGroup(MainJFrame ws, JPanel csp) {
		this.ws = ws;
		this.csp = csp;
		initComponents();

		img.setIcon(new ImageIcon("resources/create.jpg"));
		setBackground(Color.WHITE);

		results.setRowHeight(30);
		results.getColumnModel().getColumn(2).setMaxWidth(0);

		DefaultTableModel table = (DefaultTableModel) results.getModel();
		int n = table.getRowCount();
		while (n-- > 0) {
			table.removeRow(n);
		}

		txtSearch
		    .getDocument().addDocumentListener(new DocumentListener() {
			    @Override
			    public void insertUpdate(DocumentEvent e) {
				    populateResults();
			    }

			    @Override
			    public void removeUpdate(DocumentEvent e) {
				    populateResults();
			    }

			    @Override
			    public void changedUpdate(DocumentEvent e) {
				    populateResults();
			    }

		    });

		Action actionAdd = new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				try {
					int selectedRowIndex = results.getSelectedRow();
					String email = (String) results.getValueAt(selectedRowIndex, 2);
					Researcher researcher = ws.getResearcherDir().getById(email);

					String members = txtMembers.getText();
					String displayName = researcher.getUser().getFirstName() + " " + researcher.getUser().getLastName() + "(" + researcher.getUser().getEmail()+ ")";
					txtMembers.setText(members + displayName + ",\n");
				} catch (Exception exception) {
					exception.printStackTrace();
					JOptionPane.showMessageDialog(null, "There was an issue. Please try again.");
				}
			}
		};

		ButtonCellRenderer btnAdd = new ButtonCellRenderer(results, actionAdd, 1);

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                img = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                txtGroupName = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtMembers = new javax.swing.JTextArea();
                jLabel2 = new javax.swing.JLabel();
                txtSearch = new javax.swing.JTextField();
                jScrollPane2 = new javax.swing.JScrollPane();
                results = new javax.swing.JTable();
                btnCreate = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                pageTitle = new javax.swing.JLabel();

                jLabel1.setText("Group name*");

                txtMembers.setColumns(20);
                txtMembers.setRows(5);
                jScrollPane1.setViewportView(txtMembers);

                jLabel2.setText("Group members*");

                txtSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtSearchActionPerformed(evt);
                        }
                });

                results.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null}
                        },
                        new String [] {
                                "Name", "Action", ""
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                true, true, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                results.setColumnSelectionAllowed(true);
                jScrollPane2.setViewportView(results);
                results.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                if (results.getColumnModel().getColumnCount() > 0) {
                        results.getColumnModel().getColumn(0).setResizable(false);
                        results.getColumnModel().getColumn(2).setResizable(false);
                }

                btnCreate.setBackground(new java.awt.Color(0, 102, 102));
                btnCreate.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
                btnCreate.setForeground(new java.awt.Color(255, 255, 255));
                btnCreate.setText("Create group");
                btnCreate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCreateActionPerformed(evt);
                        }
                });

                jLabel3.setText("Search for your teammates");

                pageTitle.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
                pageTitle.setForeground(new java.awt.Color(51, 51, 51));
                pageTitle.setText("Create a research group");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGroupName)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                                        .addComponent(txtSearch)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(220, 220, 220)
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtSearchActionPerformed

        private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
		String[] fullNames = txtMembers.getText().trim().split("\\),");

		List<Researcher> members = new ArrayList<>();
		for (String a : fullNames) {
			String[] extractData = a.trim().split("\\(");
			String email = extractData[1];

			Researcher r = this.ws.getResearcherDir().fetchByEmail(email);

			members.add(r);
		}

		this.ws.getResearchGroups().createGroup(this.ws.getLoggedUser().getEmail(), members);

		JOptionPane.showMessageDialog(this, "Group " + txtGroupName.getText().trim()   +" successfully created!");



        }//GEN-LAST:event_btnCreateActionPerformed

	private void populateResults() {
		String query = txtSearch.getText().trim();

		DefaultTableModel table = (DefaultTableModel) results.getModel();

		int n = table.getRowCount();
		while (n-- > 0) {
			table.removeRow(n);
		}

		List<Researcher> researchers = this.ws.getResearcherDir().fetchByQuery(query);

		for (Researcher rg : researchers) {
			Vector<String> row = new Vector<>();
			String name = rg.getUser().getFirstName() + " " + rg.getUser().getLastName();
			row.add(name);
			row.add("Add");
			row.add(rg.getUser().getEmail());

			table.addRow(row);
		}

	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCreate;
        private javax.swing.JLabel img;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel pageTitle;
        private javax.swing.JTable results;
        private javax.swing.JTextField txtGroupName;
        private javax.swing.JTextArea txtMembers;
        private javax.swing.JTextField txtSearch;
        // End of variables declaration//GEN-END:variables
}
