/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import constants.Course;
import directory.ProfessorDirectory;
import directory.UniClassDirectory;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.UniClass;
import model.professor.Professor;
import ui.MainJFrame;

/**
 *
 * @author drag
 */
public class ViewProfessorsJPanel extends javax.swing.JPanel {

	private MainJFrame workSpace;
	private ProfessorDirectory profDir;
	private UniClassDirectory uniClassDir;
	/**
	 * Creates new form ViewProfessorsJPanel
	 */
	public ViewProfessorsJPanel(MainJFrame workSpace) {
		this.workSpace = workSpace;
		this.profDir = this.workSpace.getProfDir();
		this.uniClassDir = this.workSpace.getUniClassDir();

		initComponents();
		table.setRowHeight(30);

		this.workSpace.add(this);
		this.workSpace.pack();

		this.populateTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pageTitle = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                table = new javax.swing.JTable();

                pageTitle.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                pageTitle.setText("View professor statistics");

                table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Name", "Teaches", "Employer rating", "No. of students"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false, true
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(table);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel pageTitle;
        private javax.swing.JTable table;
        // End of variables declaration//GEN-END:variables

	private void populateTable() {
		List<Professor> professors = this.profDir.getDirectory();

		DefaultTableModel tbl = (DefaultTableModel) table.getModel();

		int n = tbl.getRowCount();
		while (n-- > 0) {
			tbl.removeRow(n);
		}

		for (Professor p : professors) {
			var classes = this.uniClassDir.getProfClasses(p);
			if (classes.isEmpty()) continue;	

			var classStudentNumberData = this.uniClassDir.getClassStudentData(p, classes);

			Vector<String> mainrow = new Vector<>();
				mainrow.add(p.getUserProfile().getPerson().getFullName());
				mainrow.add(classes.get(0).getFullCourseName().toString());
				mainrow.add(String.valueOf(Float.isNaN(p.getAvgEmployerRating()) ? "0" : p.getAvgEmployerRating()));
				mainrow.add(String.valueOf(classes.get(0).getNumberOfStudents()));
				int i = 0;
			for (UniClass uc : classes) {

				Vector<String> row = new Vector<>();
				row.add("");
				row.add(uc.getFullCourseName());
				row.add("");
				row.add(String.valueOf(uc.getNumberOfStudents()));
				if (i == 0) {
					tbl.addRow(mainrow);
					++i;
					continue;	
				}
				tbl.addRow(row);
			}
		}
	}
}
