/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.student;

import model.User;
import model.student.Student;
import ui.MainJFrame;
import ui.transcript.TranscriptJPanel;

/**
 *
 * @author Admin
 */
public class StudentWorkarea extends javax.swing.JPanel {

	private User user = null;
	private Student student = null;
	private MainJFrame workSpace = null;
	private ProgressJPanel progressPanel = null;
	private BrowseCoursesJPanel browseCoursesPanel = null;
	private EditProfileJPanel editProfilePanel = null;
	private NotificationsJPanel notificationsPanel = null;
	private TranscriptJPanel transcriptPanel = null;

	/**
	 * Creates new form student_loginJPanel
	 */
	public StudentWorkarea(MainJFrame workSpace, User user) {
		this.workSpace = workSpace;
		this.user = user;
		this.student = this.workSpace.getStudentDir().getStudent(this.user);

		initComponents();

		this.workSpace.add(this);
		this.workSpace.pack();

		this.btnTranscript.setEnabled(this.student.getTranscript().isGraduated() && this.student.isGraduated());
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                splitPane = new javax.swing.JSplitPane();
                leftPane = new javax.swing.JPanel();
                btnMyLearning = new javax.swing.JButton();
                btnBrowseCourses = new javax.swing.JButton();
                btnLogout = new javax.swing.JButton();
                btnNotifications = new javax.swing.JButton();
                btnTranscript = new javax.swing.JButton();
                btnViewProfile = new javax.swing.JButton();
                StudentCardLayout = new javax.swing.JPanel();

                leftPane.setBackground(new java.awt.Color(153, 204, 255));

                btnMyLearning.setText("My learning");
                btnMyLearning.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMyLearningActionPerformed(evt);
                        }
                });

                btnBrowseCourses.setText("Browse courses");
                btnBrowseCourses.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBrowseCoursesActionPerformed(evt);
                        }
                });

                btnLogout.setText("<< Logout");
                btnLogout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLogoutActionPerformed(evt);
                        }
                });

                btnNotifications.setText("Notifications");
                btnNotifications.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNotificationsActionPerformed(evt);
                        }
                });

                btnTranscript.setText("View transcript");
                btnTranscript.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTranscriptActionPerformed(evt);
                        }
                });

                btnViewProfile.setText("View profile");
                btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnViewProfileActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout leftPaneLayout = new javax.swing.GroupLayout(leftPane);
                leftPane.setLayout(leftPaneLayout);
                leftPaneLayout.setHorizontalGroup(
                        leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(leftPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnMyLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBrowseCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLogout)
                                        .addComponent(btnNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPaneLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                leftPaneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBrowseCourses, btnLogout, btnMyLearning, btnNotifications});

                leftPaneLayout.setVerticalGroup(
                        leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(leftPaneLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(btnMyLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnBrowseCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                .addComponent(btnLogout)
                                .addGap(49, 49, 49))
                );

                leftPaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBrowseCourses, btnMyLearning, btnNotifications, btnTranscript, btnViewProfile});

                splitPane.setLeftComponent(leftPane);

                StudentCardLayout.setBackground(new java.awt.Color(255, 204, 204));
                StudentCardLayout.setLayout(new java.awt.CardLayout());
                splitPane.setRightComponent(StudentCardLayout);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(splitPane)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnMyLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyLearningActionPerformed
		this.progressPanel = new ProgressJPanel(this.workSpace, this.user);
		splitPane.setRightComponent(this.progressPanel);
        }//GEN-LAST:event_btnMyLearningActionPerformed

        private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
		this.workSpace.getInitJPanel().setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_btnLogoutActionPerformed

        private void btnBrowseCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseCoursesActionPerformed
		this.browseCoursesPanel = new BrowseCoursesJPanel(this.workSpace);
		splitPane.setRightComponent(this.browseCoursesPanel);
        }//GEN-LAST:event_btnBrowseCoursesActionPerformed

        private void btnNotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationsActionPerformed
		this.notificationsPanel = new NotificationsJPanel(this.workSpace);
		splitPane.setRightComponent(this.notificationsPanel);

        }//GEN-LAST:event_btnNotificationsActionPerformed

        private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
		this.transcriptPanel = new TranscriptJPanel(this.workSpace, this.student.getTranscript());
		splitPane.setRightComponent(this.transcriptPanel);
        }//GEN-LAST:event_btnTranscriptActionPerformed

        private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
		this.editProfilePanel = new EditProfileJPanel(this.workSpace);
		splitPane.setRightComponent(this.editProfilePanel);
        }//GEN-LAST:event_btnViewProfileActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel StudentCardLayout;
        private javax.swing.JButton btnBrowseCourses;
        private javax.swing.JButton btnLogout;
        private javax.swing.JButton btnMyLearning;
        private javax.swing.JButton btnNotifications;
        private javax.swing.JButton btnTranscript;
        private javax.swing.JButton btnViewProfile;
        private javax.swing.JPanel leftPane;
        private javax.swing.JSplitPane splitPane;
        // End of variables declaration//GEN-END:variables
}
